version: '2'
services:
    external-app:
        image: external
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://external-mysql:3306/external?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    external-mysql:
        extends:
            file: mysql.yml
            service: external-mysql
